In [1]:
import numpy as np

In [13]:
arr1D = [1, 2, 3, 4]
arr1D

[1, 2, 3, 4]

In [14]:
arr2D = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
arr2D

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
arrArange1 = np.arange(10)
arrArange2 = np.arange(2, 9)
arrArange3 = np.arange(2, 12, 3)
arrArange4 = np.arange(1, 10, 2, float)

print(arrArange1)
print(arrArange2)
print(arrArange3)
print(arrArange4)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]
[ 2  5  8 11]
[1. 3. 5. 7. 9.]


In [20]:
arrLins1 = np.linspace(2, 3, 100)
arrLins2 = np.linspace(2, 3, 10)
arrLins3 = np.linspace(2, 3, 10, dtype=int)
arrLins4 = np.linspace(2, 3, 10, retstep=True)

print(arrLins1) # akan ada sebanyak 50 data berjarak sama dari 2 sampai 3
print()
print(arrLins2) # Output: [2.   2.25 2.5  2.75 3.  ]
print()
print(arrLins3) # Output: [2 2 2 2 3]
print()
print(arrLins4) # Output: (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

[2.         2.01010101 2.02020202 2.03030303 2.04040404 2.05050505
 2.06060606 2.07070707 2.08080808 2.09090909 2.1010101  2.11111111
 2.12121212 2.13131313 2.14141414 2.15151515 2.16161616 2.17171717
 2.18181818 2.19191919 2.2020202  2.21212121 2.22222222 2.23232323
 2.24242424 2.25252525 2.26262626 2.27272727 2.28282828 2.29292929
 2.3030303  2.31313131 2.32323232 2.33333333 2.34343434 2.35353535
 2.36363636 2.37373737 2.38383838 2.39393939 2.4040404  2.41414141
 2.42424242 2.43434343 2.44444444 2.45454545 2.46464646 2.47474747
 2.48484848 2.49494949 2.50505051 2.51515152 2.52525253 2.53535354
 2.54545455 2.55555556 2.56565657 2.57575758 2.58585859 2.5959596
 2.60606061 2.61616162 2.62626263 2.63636364 2.64646465 2.65656566
 2.66666667 2.67676768 2.68686869 2.6969697  2.70707071 2.71717172
 2.72727273 2.73737374 2.74747475 2.75757576 2.76767677 2.77777778
 2.78787879 2.7979798  2.80808081 2.81818182 2.82828283 2.83838384
 2.84848485 2.85858586 2.86868687 2.87878788 2.88888889 2.89898

In [24]:
arrZero1 = np.zeros(5)
arrZero2 = np.ones(5, dtype=int)
arrZero3 = np.zeros((3, 4))
arrZero4 = np.ones((3, 4, 5), dtype=int)

print(arrZero1) # Output: [0. 0. 0. 0. 0.]
print()
print(arrZero2) # Output: [0 0 0 0 0]
print()
print(arrZero3)
print()
print(arrZero4)

[0. 0. 0. 0. 0.]

[1 1 1 1 1]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [30]:
arrEmpty1 = np.empty(5, int)
arrEmpty2 = np.empty((3, 4))

print(arrEmpty1) # Apakah arraynya memiliki isi?
print(arrEmpty2) # Apakah arraynya memiliki isi?

print(arrEmpty2.size)

[4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
12


In [10]:
massive_array = np.random.random(100000)

In [11]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

4.68 ms ± 98.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
23.6 µs ± 791 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
